<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $policies = [
            "7-day return policy for defective items.",
            "Returns accepted within 14 days of delivery.",
            "Easy 30-day return and exchange policy.",
            "Hassle-free returns within 7 days.",
            "Products can be returned in original condition within 15 days.",
            "Customer satisfaction guaranteed with easy returns.",
            "Return eligible items within 30 days for refund or replacement.",
            "Unused items may be returned within 14 days.",
            "Simple returns process with fast refund approval.",
            "Exchange or refund available for eligible products.",
        ];

        $products = [

            // Image 1 - CCTV Camera (Electronics)
            [
                'title'       => 'Outdoor Bullet Security Camera 1080P HD',
                'category_id' => 1,
                'brand_id'    => 1,
                'price'       => 4999.00,
                'sale_price'  => 3499.00,
                'stock_qty'   => 80,
                'featured'    => true,
                'weight'      => 0.45,
                'thumbnail'   => 'mock/products/1.jpg',
                'excerpt'     => '1080P HD outdoor bullet camera with night vision and weatherproof housing.',
                'description' => 'Full HD 1080P outdoor security camera with 24 IR LEDs for night vision up to 20m. IP66 weatherproof rating, wide-angle lens, and easy wall-mount bracket included. Compatible with most DVR/NVR systems.',
                'meta_title'       => 'Outdoor Bullet Security Camera 1080P HD | Best Price',
                'meta_keywords'    => 'security camera, CCTV, outdoor camera, 1080p, night vision',
                'meta_description' => 'Buy 1080P HD outdoor bullet security camera with night vision at best price.',
            ],

            // Image 2 - Purple Bodycon Dress (Fashion - Women)
            [
                'title'       => 'Elegant Bow-Detail Bodycon Midi Dress',
                'category_id' => 2,
                'brand_id'    => 2,
                'price'       => 5499.00,
                'sale_price'  => 3999.00,
                'stock_qty'   => 120,
                'featured'    => true,
                'weight'      => 0.35,
                'thumbnail'   => 'mock/products/2.jpg',
                'excerpt'     => 'Elegant purple bodycon midi dress with 3/4 sleeves and bow detail.',
                'description' => 'Sophisticated bodycon midi dress featuring a stylish bow accent at the waist. 3/4 length sleeves with crew neckline. Stretchy fabric blend for a flattering fit. Perfect for office wear, dinner dates, or formal events. Available in sizes S-XL.',
                'meta_title'       => 'Elegant Bow-Detail Bodycon Midi Dress | Women Fashion',
                'meta_keywords'    => 'bodycon dress, midi dress, purple dress, women fashion, formal dress',
                'meta_description' => 'Shop elegant bow-detail bodycon midi dress for women. Perfect for formal occasions.',
            ],

            // Image 3 - Pink Hooded Puffer Jacket (Fashion - Women)
            [
                'title'       => 'Women\'s Short Hooded Puffer Jacket',
                'category_id' => 2,
                'brand_id'    => 2,
                'price'       => 8999.00,
                'sale_price'  => 6499.00,
                'stock_qty'   => 90,
                'featured'    => false,
                'weight'      => 0.70,
                'thumbnail'   => 'mock/products/3.jpg',
                'excerpt'     => 'Warm and stylish short hooded puffer jacket for women.',
                'description' => 'Trendy short puffer jacket with detachable hood and badge patch details. Thick padded fill for superior warmth. Ribbed cuffs and hem for a snug fit. Side zip pockets. Available in multiple colors. Perfect for winter and casual outings.',
                'meta_title'       => 'Women\'s Short Hooded Puffer Jacket | Winter Collection',
                'meta_keywords'    => 'puffer jacket, hooded jacket, women winter jacket, padded jacket',
                'meta_description' => 'Stay warm in style with our women\'s short hooded puffer jacket. Shop now.',
            ],

            // Image 4 - Batwing Knit Mini Dress (Fashion - Women)
            [
                'title'       => 'Glitter Batwing Sleeve Knit Mini Dress',
                'category_id' => 2,
                'brand_id'    => 2,
                'price'       => 6499.00,
                'sale_price'  => 4999.00,
                'stock_qty'   => 75,
                'featured'    => false,
                'weight'      => 0.30,
                'thumbnail'   => 'mock/products/4.jpg',
                'excerpt'     => 'Shimmery batwing sleeve knit mini dress with long chain necklace.',
                'description' => 'Eye-catching mini dress in glitter knit fabric with dramatic batwing sleeves and scoop neck. Stretchy and comfortable for all-night wear. Pair with heels and statement jewelry for a complete look. Dry clean recommended.',
                'meta_title'       => 'Glitter Batwing Sleeve Knit Mini Dress | Party Wear',
                'meta_keywords'    => 'mini dress, batwing dress, party dress, glitter dress, knit dress',
                'meta_description' => 'Shop glitter batwing sleeve knit mini dress. Perfect for parties and nights out.',
            ],

            // Image 5 - Beaded Evening Dress (Fashion - Women)
            [
                'title'       => 'Luxury Beaded Lace Bodycon Evening Dress',
                'category_id' => 2,
                'brand_id'    => 3,
                'price'       => 18999.00,
                'sale_price'  => 15999.00,
                'stock_qty'   => 30,
                'featured'    => true,
                'weight'      => 0.55,
                'thumbnail'   => 'mock/products/5.jpg',
                'excerpt'     => 'Stunning beaded lace evening dress with sheer illusion neckline.',
                'description' => 'Exquisite evening dress with intricate hand-beaded lace overlay on the bodice. Sheer illusion neckline and 3/4 sleeves. Nude underlining with form-fitting silhouette. Perfect for weddings, galas, and formal events. Dry clean only.',
                'meta_title'       => 'Luxury Beaded Lace Evening Dress | Formal Wear',
                'meta_keywords'    => 'evening dress, beaded dress, lace dress, formal dress, wedding guest',
                'meta_description' => 'Shop luxury beaded lace bodycon evening dress for special occasions.',
            ],

            // Image 6 - Pink Long Puffer Coat (Fashion - Women)
            [
                'title'       => 'Women\'s Long Quilted Hooded Winter Coat',
                'category_id' => 2,
                'brand_id'    => 2,
                'price'       => 14999.00,
                'sale_price'  => 11999.00,
                'stock_qty'   => 60,
                'featured'    => true,
                'weight'      => 1.20,
                'thumbnail'   => 'mock/products/6.jpg',
                'excerpt'     => 'Premium long quilted winter coat with knit scarf hood.',
                'description' => 'Elegant long winter coat with unique knit-style oversized hood for extra warmth. Diamond-quilted pattern, asymmetric zipper closure, and side seam pockets. Water-resistant outer shell. Flattering A-line silhouette. Available in sizes XS-XXL.',
                'meta_title'       => 'Women\'s Long Quilted Hooded Winter Coat | Premium',
                'meta_keywords'    => 'winter coat, long coat, quilted coat, hooded coat, women outerwear',
                'meta_description' => 'Stay warm and stylish in our premium long quilted hooded winter coat.',
            ],

            // Image 7 - Pink Swing Dress (Fashion - Women)
            [
                'title'       => 'Casual Marled Knit Long Sleeve Swing Dress',
                'category_id' => 2,
                'brand_id'    => 2,
                'price'       => 3999.00,
                'sale_price'  => 2999.00,
                'stock_qty'   => 150,
                'featured'    => false,
                'weight'      => 0.28,
                'thumbnail'   => 'mock/products/7.jpg',
                'excerpt'     => 'Cozy marled knit swing dress perfect for casual everyday wear.',
                'description' => 'Relaxed fit swing dress in soft marled knit fabric. Round neckline, long sleeves, and flowy A-line silhouette. Lightweight and breathable — great for layering. Machine washable. Available in multiple colors and sizes XS-XL.',
                'meta_title'       => 'Casual Marled Knit Long Sleeve Swing Dress',
                'meta_keywords'    => 'swing dress, knit dress, casual dress, long sleeve dress, everyday dress',
                'meta_description' => 'Shop cozy marled knit swing dress for everyday casual wear.',
            ],

            // Image 8 - Red Puffer Jacket (Fashion - Women)
            [
                'title'       => 'Women\'s Hooded Padded Puffer Jacket Red',
                'category_id' => 2,
                'brand_id'    => 2,
                'price'       => 7999.00,
                'sale_price'  => 5999.00,
                'stock_qty'   => 100,
                'featured'    => false,
                'weight'      => 0.65,
                'thumbnail'   => 'mock/products/8.jpg',
                'excerpt'     => 'Bold red hooded puffer jacket with zip pockets and badge detail.',
                'description' => 'Vibrant red padded puffer jacket with fixed hood and contrast zip details. Two front zip pockets and adjustable hem drawstring. Warm polyester fill for cold weather. Slim fit design. Available in red, black, and navy.',
                'meta_title'       => 'Women\'s Hooded Padded Puffer Jacket | Winter Wear',
                'meta_keywords'    => 'puffer jacket, red jacket, hooded jacket, winter jacket, padded coat',
                'meta_description' => 'Shop women\'s hooded padded puffer jacket in bold red. Perfect for winter.',
            ],

            // Image 9 - Faux Fur Vest (Fashion - Women)
            [
                'title'       => 'Multicolor Striped Faux Fur Vest',
                'category_id' => 2,
                'brand_id'    => 2,
                'price'       => 6999.00,
                'sale_price'  => 5499.00,
                'stock_qty'   => 80,
                'featured'    => true,
                'weight'      => 0.40,
                'thumbnail'   => 'mock/products/9.jpg',
                'excerpt'     => 'Luxurious multicolor striped faux fur sleeveless vest.',
                'description' => 'Statement faux fur vest in bold blue, white and beige stripe pattern. Open-front design with no closure for easy layering. Soft and fluffy texture. Pair with jeans and a plain tee for an effortlessly chic look. Hand wash cold.',
                'meta_title'       => 'Multicolor Striped Faux Fur Vest | Women Fashion',
                'meta_keywords'    => 'faux fur vest, fur vest, striped vest, women vest, winter fashion',
                'meta_description' => 'Shop multicolor striped faux fur vest for women. Trendy winter fashion.',
            ],

            // Image 10 - Teddy Coat (Fashion - Women)
            [
                'title'       => 'Oversized Teddy Bear Faux Fur Long Coat',
                'category_id' => 2,
                'brand_id'    => 2,
                'price'       => 16999.00,
                'sale_price'  => 13999.00,
                'stock_qty'   => 45,
                'featured'    => true,
                'weight'      => 1.10,
                'thumbnail'   => 'mock/products/10.jpg',
                'excerpt'     => 'Ultra-soft oversized teddy bear faux fur long coat.',
                'description' => 'Luxuriously soft teddy bear faux fur coat in a relaxed oversized silhouette. Single button closure with wide lapel collar. Drop shoulders and roomy fit. Lined interior for extra warmth. A must-have winter statement piece.',
                'meta_title'       => 'Oversized Teddy Bear Faux Fur Long Coat | Luxury',
                'meta_keywords'    => 'teddy coat, faux fur coat, oversized coat, long coat, winter coat',
                'meta_description' => 'Shop oversized teddy bear faux fur long coat. Ultimate winter luxury.',
            ],

            // Image 11 - Orange Turtleneck (Fashion - Women)
            [
                'title'       => 'Oversized Ribbed Turtleneck Sweater Orange',
                'category_id' => 2,
                'brand_id'    => 2,
                'price'       => 5499.00,
                'sale_price'  => 3999.00,
                'stock_qty'   => 130,
                'featured'    => false,
                'weight'      => 0.50,
                'thumbnail'   => 'mock/products/11.jpg',
                'excerpt'     => 'Chunky ribbed oversized turtleneck sweater with stripe cuff detail.',
                'description' => 'Bold orange oversized turtleneck sweater in thick ribbed knit. Relaxed boxy fit with dropped shoulders and flared cuffs with stripe contrast detail. Soft and warm acrylic blend. Great for layering or wearing alone.',
                'meta_title'       => 'Oversized Ribbed Turtleneck Sweater | Women Knitwear',
                'meta_keywords'    => 'turtleneck sweater, ribbed sweater, oversized sweater, knitwear, orange sweater',
                'meta_description' => 'Shop oversized ribbed turtleneck sweater in bold orange.',
            ],

            // Image 12 - Black Turtleneck (Fashion - Women)
            [
                'title'       => 'Classic Ribbed Turtleneck Sweater Black',
                'category_id' => 2,
                'brand_id'    => 2,
                'price'       => 5499.00,
                'sale_price'  => 3999.00,
                'stock_qty'   => 160,
                'featured'    => false,
                'weight'      => 0.50,
                'thumbnail'   => 'mock/products/12.jpg',
                'excerpt'     => 'Timeless black ribbed turtleneck with contrast stripe cuff.',
                'description' => 'Classic black ribbed turtleneck sweater with a modern boxy silhouette. Features contrast stripe cuffs for a chic finishing touch. Soft acrylic-wool blend, warm and comfortable. Versatile wardrobe staple — pairs with everything.',
                'meta_title'       => 'Classic Ribbed Turtleneck Sweater Black | Women Knitwear',
                'meta_keywords'    => 'black turtleneck, ribbed sweater, turtleneck sweater, knitwear, women tops',
                'meta_description' => 'Shop classic black ribbed turtleneck sweater for women.',
            ],

            // Image 13 - Checkered Jacket + Wide Pants (Fashion - Women)
            [
                'title'       => 'Plaid Cropped Jacket & Wide-Leg Pants Set',
                'category_id' => 2,
                'brand_id'    => 3,
                'price'       => 12999.00,
                'sale_price'  => 9999.00,
                'stock_qty'   => 55,
                'featured'    => true,
                'weight'      => 0.75,
                'thumbnail'   => 'mock/products/13.jpg',
                'excerpt'     => 'Co-ord set featuring plaid cropped jacket and wide-leg trousers.',
                'description' => 'Chic two-piece co-ord set with a button-front plaid cropped jacket and matching wide-leg trousers with contrast side stripe. Modern and minimalist design. Dry clean recommended. Sold as a set.',
                'meta_title'       => 'Plaid Cropped Jacket & Wide-Leg Pants Co-ord Set',
                'meta_keywords'    => 'co-ord set, plaid jacket, wide leg pants, two piece set, women fashion',
                'meta_description' => 'Shop plaid cropped jacket and wide-leg pants co-ord set for women.',
            ],

            // Image 14 - Knit Hat + Neck Warmer Set (Fashion - Men)
            [
                'title'       => 'Men\'s Knit Beanie & Neck Warmer Winter Set',
                'category_id' => 3,
                'brand_id'    => 4,
                'price'       => 2499.00,
                'sale_price'  => 1799.00,
                'stock_qty'   => 200,
                'featured'    => false,
                'weight'      => 0.18,
                'thumbnail'   => 'mock/products/14.jpg',
                'excerpt'     => 'Warm knit beanie and neck warmer set with fleece lining.',
                'description' => 'Two-piece winter set including a slouchy knit beanie and matching neck gaiter. Soft fleece lining for extra warmth. Elastic neck warmer doubles as a face mask. One size fits most. Great for outdoor activities in cold weather.',
                'meta_title'       => 'Men\'s Knit Beanie & Neck Warmer Set | Winter Accessories',
                'meta_keywords'    => 'beanie, neck warmer, winter set, knit hat, men accessories',
                'meta_description' => 'Shop men\'s knit beanie and neck warmer winter set. Stay warm outdoors.',
            ],

            // Image 15 - Cashmere Scarf (Fashion - Accessories)
            [
                'title'       => 'Pure Cashmere Solid Fringe Scarf Ivory',
                'category_id' => 3,
                'brand_id'    => 4,
                'price'       => 3999.00,
                'sale_price'  => 2999.00,
                'stock_qty'   => 180,
                'featured'    => false,
                'weight'      => 0.20,
                'thumbnail'   => 'mock/products/15.jpg',
                'excerpt'     => 'Luxuriously soft pure cashmere scarf with fringe ends in ivory.',
                'description' => 'Classic solid ivory cashmere scarf with delicate fringe trim. Ultra-soft, lightweight, and warm. Large wrap size for versatile styling — wear as a scarf, shawl, or wrap. Dry clean only. Available in multiple colors.',
                'meta_title'       => 'Pure Cashmere Solid Fringe Scarf | Luxury Accessories',
                'meta_keywords'    => 'cashmere scarf, luxury scarf, fringe scarf, ivory scarf, winter accessories',
                'meta_description' => 'Shop pure cashmere solid fringe scarf in ivory. Luxurious warmth.',
            ],

            // Image 16 - Men's Cardigan (Fashion - Men)
            [
                'title'       => 'Men\'s Open-Front Knit Cardigan Sweater',
                'category_id' => 3,
                'brand_id'    => 4,
                'price'       => 6999.00,
                'sale_price'  => 5499.00,
                'stock_qty'   => 110,
                'featured'    => false,
                'weight'      => 0.60,
                'thumbnail'   => 'mock/products/16.jpg',
                'excerpt'     => 'Classic open-front men\'s cardigan in premium knit fabric.',
                'description' => 'Versatile open-front cardigan in a fine-knit marled fabric. No buttons — relaxed draped front. Ribbed cuffs and hem. Pairs perfectly with a shirt and trousers or casual jeans. Available in grey, blue, and camel. Machine washable.',
                'meta_title'       => 'Men\'s Open-Front Knit Cardigan Sweater | Men Fashion',
                'meta_keywords'    => 'cardigan, men cardigan, knit sweater, open front cardigan, men fashion',
                'meta_description' => 'Shop men\'s open-front knit cardigan sweater. Versatile and stylish.',
            ],

            // Image 17 - Men's Suit (Fashion - Men)
            [
                'title'       => 'Men\'s Slim Fit Single Button Formal Suit',
                'category_id' => 3,
                'brand_id'    => 5,
                'price'       => 29999.00,
                'sale_price'  => 24999.00,
                'stock_qty'   => 40,
                'featured'    => true,
                'weight'      => 1.50,
                'thumbnail'   => 'mock/products/17.jpg',
                'excerpt'     => 'Sharp slim-fit formal suit with single button closure.',
                'description' => 'Premium slim-fit men\'s suit in solid black. Single button notch lapel jacket with flap pockets and matching flat-front trousers. Fully lined. Perfect for business meetings, weddings, and formal occasions. Available in sizes 36–52.',
                'meta_title'       => 'Men\'s Slim Fit Formal Suit | Business & Wedding',
                'meta_keywords'    => 'men suit, formal suit, slim fit suit, black suit, business suit',
                'meta_description' => 'Shop men\'s slim fit single button formal suit. Perfect for all occasions.',
            ],

            // Image 18 - Men's Knit Cap + Scarf Set (Fashion - Men)
            [
                'title'       => 'Men\'s Fleece-Lined Visor Beanie & Scarf Set',
                'category_id' => 3,
                'brand_id'    => 4,
                'price'       => 2999.00,
                'sale_price'  => 1999.00,
                'stock_qty'   => 220,
                'featured'    => false,
                'weight'      => 0.22,
                'thumbnail'   => 'mock/products/18.jpg',
                'excerpt'     => 'Warm fleece-lined visor beanie and neck scarf winter set for men.',
                'description' => 'Two-piece men\'s winter set with a thick fleece-lined visor beanie and matching ring scarf. Knit exterior with soft inner fleece for maximum warmth. Visor brim for sun protection. Great for skiing, hiking, or daily commute.',
                'meta_title'       => 'Men\'s Fleece-Lined Visor Beanie & Scarf Set',
                'meta_keywords'    => 'visor beanie, fleece beanie, men winter set, knit cap, neck scarf',
                'meta_description' => 'Shop men\'s fleece-lined visor beanie and scarf winter set.',
            ],

            // Image 19 - Smart Fitness Band (Electronics)
            [
                'title'       => 'Smart Fitness Band with Heart Rate Monitor',
                'category_id' => 1,
                'brand_id'    => 1,
                'price'       => 3499.00,
                'sale_price'  => 2499.00,
                'stock_qty'   => 300,
                'featured'    => true,
                'weight'      => 0.025,
                'thumbnail'   => 'mock/products/19.jpg',
                'excerpt'     => 'Feature-packed fitness tracker with OLED display and heart rate monitor.',
                'description' => 'Smart fitness band with 0.96" OLED display, continuous heart rate monitoring, step counter, calorie tracker, and sleep monitor. IP67 waterproof. 7-day battery life. Compatible with iOS and Android. Available in multiple strap colors.',
                'meta_title'       => 'Smart Fitness Band Heart Rate Monitor | Best Price',
                'meta_keywords'    => 'fitness band, smart band, heart rate monitor, activity tracker, smartwatch',
                'meta_description' => 'Buy smart fitness band with heart rate monitor. Track your health 24/7.',
            ],

            // Image 20 - Power Bank (Electronics)
            [
                'title'       => '20000mAh Dual USB Portable Power Bank',
                'category_id' => 1,
                'brand_id'    => 1,
                'price'       => 4999.00,
                'sale_price'  => 3499.00,
                'stock_qty'   => 250,
                'featured'    => true,
                'weight'      => 0.38,
                'thumbnail'   => 'mock/products/20.jpg',
                'excerpt'     => 'High-capacity 20000mAh power bank with LED display and dual USB output.',
                'description' => 'Compact 20000mAh power bank with dual USB-A outputs and USB-C input. LED battery indicator display. Fast charging support up to 18W. Charges smartphones 4-5 times. Slim aluminum body available in black and silver. Includes USB-C cable.',
                'meta_title'       => '20000mAh Dual USB Portable Power Bank | Fast Charging',
                'meta_keywords'    => 'power bank, 20000mah, portable charger, fast charging, dual USB',
                'meta_description' => 'Buy 20000mAh dual USB portable power bank with LED display.',
            ],
            // Add these to the $products array in ProductSeeder

            // Image 21 - Baby Musical Drum Toy (Baby & Toddler)
            [
                'title'       => 'Baby Musical Light-Up Drum Toy',
                'category_id' => 5,
                'brand_id'    => 6,
                'price'       => 2499.00,
                'sale_price'  => 1799.00,
                'stock_qty'   => 200,
                'featured'    => true,
                'weight'      => 0.30,
                'thumbnail'   => 'mock/products/21.jpg',
                'excerpt'     => 'Interactive baby drum toy with colorful lights and music.',
                'description' => 'Fun light-up musical drum toy for babies aged 6 months and above. Features colorful LED lights and plays fun melodies when tapped. Stimulates sensory development and hand-eye coordination. Made from non-toxic BPA-free materials. Battery operated.',
                'meta_title'       => 'Baby Musical Light-Up Drum Toy | Educational Toys',
                'meta_keywords'    => 'baby toy, musical toy, drum toy, light up toy, infant toy',
                'meta_description' => 'Shop baby musical light-up drum toy. Great for sensory development.',
            ],

            // Image 22 - Apple iPad Mini (Electronics)
            [
                'title'       => 'Apple iPad Mini 4 Wi-Fi 128GB Silver',
                'category_id' => 1,
                'brand_id'    => 2,
                'price'       => 59999.00,
                'sale_price'  => 52999.00,
                'stock_qty'   => 35,
                'featured'    => true,
                'weight'      => 0.299,
                'thumbnail'   => 'mock/products/22.jpg',
                'excerpt'     => 'Compact Apple iPad Mini 4 with 7.9" Retina display and A8 chip.',
                'description' => 'Apple iPad Mini 4 with 7.9-inch Retina display, A8 chip, 128GB storage, and Wi-Fi. Ultra-thin and lightweight design. Touch ID fingerprint sensor. Up to 10 hours battery life. Compatible with Apple Pencil and Smart Keyboard. iOS ready.',
                'meta_title'       => 'Apple iPad Mini 4 128GB Silver | Best Price',
                'meta_keywords'    => 'iPad mini, Apple tablet, iPad mini 4, Apple iPad, tablet',
                'meta_description' => 'Buy Apple iPad Mini 4 Wi-Fi 128GB Silver at best price.',
            ],

            // Image 23 - Apple iPad Pro (Electronics)
            [
                'title'       => 'Apple iPad Pro 10.5" 64GB Space Grey',
                'category_id' => 1,
                'brand_id'    => 2,
                'price'       => 89999.00,
                'sale_price'  => 79999.00,
                'stock_qty'   => 25,
                'featured'    => true,
                'weight'      => 0.469,
                'thumbnail'   => 'mock/products/23.jpg',
                'excerpt'     => 'Powerful iPad Pro with 10.5" ProMotion display and A10X Fusion chip.',
                'description' => 'Apple iPad Pro 10.5-inch with stunning ProMotion 120Hz display, A10X Fusion chip, and 64GB storage. Supports Apple Pencil and Smart Keyboard. 12MP rear camera, 7MP FaceTime camera. Wi-Fi + optional LTE. Up to 10 hours battery.',
                'meta_title'       => 'Apple iPad Pro 10.5 inch 64GB | Space Grey',
                'meta_keywords'    => 'iPad Pro, Apple tablet, iPad 10.5, tablet, Apple iPad Pro',
                'meta_description' => 'Buy Apple iPad Pro 10.5 inch 64GB Space Grey at best price.',
            ],

            // Image 24 - Mini Portable Projector (Electronics)
            [
                'title'       => 'Mini Portable Smart Projector with Bluetooth Speaker',
                'category_id' => 1,
                'brand_id'    => 1,
                'price'       => 24999.00,
                'sale_price'  => 19999.00,
                'stock_qty'   => 50,
                'featured'    => true,
                'weight'      => 0.55,
                'thumbnail'   => 'mock/products/24.jpg',
                'excerpt'     => 'Compact all-in-one smart projector with built-in Bluetooth speaker.',
                'description' => 'Ultra-portable mini projector with built-in Bluetooth speaker. Projects up to 100-inch screen. DLP display technology with 854x480 native resolution. Wi-Fi screen mirroring, HDMI, and USB inputs. 2-hour built-in battery. Compatible with iOS and Android.',
                'meta_title'       => 'Mini Portable Smart Projector with Bluetooth Speaker',
                'meta_keywords'    => 'mini projector, portable projector, smart projector, bluetooth projector, home cinema',
                'meta_description' => 'Shop mini portable smart projector with built-in Bluetooth speaker.',
            ],

            // Image 25 - DSLR Camera (Electronics - Cameras)
            [
                'title'       => 'Professional Full-Frame DSLR Camera Body 24MP',
                'category_id' => 1,
                'brand_id'    => 7,
                'price'       => 299999.00,
                'sale_price'  => 269999.00,
                'stock_qty'   => 15,
                'featured'    => true,
                'weight'      => 0.890,
                'thumbnail'   => 'mock/products/25.jpg',
                'excerpt'     => 'Professional full-frame 24MP DSLR with wide-angle lens kit.',
                'description' => 'Professional full-frame DSLR camera with 24.2MP CMOS sensor and DIGIC 7 image processor. 61-point AF system, 6fps continuous shooting, and 4K video recording. Weather-sealed magnesium alloy body. Includes 24-105mm f/4L IS USM lens. Dual memory card slots.',
                'meta_title'       => 'Professional Full-Frame DSLR Camera 24MP | Best Price',
                'meta_keywords'    => 'DSLR camera, professional camera, full frame camera, digital camera, camera kit',
                'meta_description' => 'Buy professional full-frame 24MP DSLR camera with lens kit at best price.',
            ],

            // Image 26 - Mini Wearable Camera (Electronics - Cameras)
            [
                'title'       => 'Mini Wearable Clip-On Action Camera 1080P',
                'category_id' => 1,
                'brand_id'    => 1,
                'price'       => 7999.00,
                'sale_price'  => 5999.00,
                'stock_qty'   => 90,
                'featured'    => false,
                'weight'      => 0.035,
                'thumbnail'   => 'mock/products/26.jpg',
                'excerpt'     => 'Ultra-compact wearable clip-on camera with 1080P recording.',
                'description' => 'Tiny wearable action camera with magnetic clip mount. Records 1080P HD video with wide-angle lens. Motion detection, loop recording, and Wi-Fi connectivity for smartphone app control. IP54 splash resistant. Built-in rechargeable battery. Perfect for cycling, vlogging, and pets.',
                'meta_title'       => 'Mini Wearable Clip-On Action Camera 1080P',
                'meta_keywords'    => 'wearable camera, clip camera, action camera, mini camera, body camera',
                'meta_description' => 'Shop mini wearable clip-on 1080P action camera. Compact and lightweight.',
            ],

            // Image 27 - Camera Sling Bag (Electronics - Accessories)
            [
                'title'       => 'Waterproof DSLR Camera Sling Shoulder Bag Orange',
                'category_id' => 1,
                'brand_id'    => 8,
                'price'       => 5999.00,
                'sale_price'  => 4499.00,
                'stock_qty'   => 120,
                'featured'    => false,
                'weight'      => 0.55,
                'thumbnail'   => 'mock/products/27.jpg',
                'excerpt'     => 'Waterproof padded DSLR camera sling bag with multiple compartments.',
                'description' => 'Stylish and durable camera sling bag in bold orange and black. Padded interior with adjustable dividers to fit DSLR body plus 2-3 lenses. Quick-access side opening. Waterproof nylon exterior with anti-scratch lining. Fits laptops up to 10 inches. Comfortable adjustable strap.',
                'meta_title'       => 'Waterproof DSLR Camera Sling Shoulder Bag | Orange',
                'meta_keywords'    => 'camera bag, sling bag, DSLR bag, camera backpack, photography bag',
                'meta_description' => 'Shop waterproof DSLR camera sling shoulder bag in orange.',
            ],

            // Image 28 - Flexible Tripod (Electronics - Accessories)
            [
                'title'       => 'Flexible Gorilla Mini Tripod for DSLR & Smartphones',
                'category_id' => 1,
                'brand_id'    => 8,
                'price'       => 2999.00,
                'sale_price'  => 1999.00,
                'stock_qty'   => 180,
                'featured'    => false,
                'weight'      => 0.28,
                'thumbnail'   => 'mock/products/28.jpg',
                'excerpt'     => 'Flexible bendable mini tripod with 360° ball head for cameras.',
                'description' => 'Versatile flexible mini tripod with bendable rubber-coated legs that wrap around any surface. Universal 1/4" screw mount fits all DSLR cameras and smartphones with adapter. 360° ball head for any angle. Compact and lightweight. Perfect for tabletop and outdoor shooting.',
                'meta_title'       => 'Flexible Gorilla Mini Tripod for DSLR & Smartphones',
                'meta_keywords'    => 'mini tripod, flexible tripod, gorilla tripod, camera stand, tripod',
                'meta_description' => 'Shop flexible gorilla mini tripod for DSLR cameras and smartphones.',
            ],

            // Image 29 - Digital Sports Watch (Electronics - Wearables)
            [
                'title'       => 'Bluetooth Digital Sports Watch with Pedometer',
                'category_id' => 1,
                'brand_id'    => 1,
                'price'       => 4999.00,
                'sale_price'  => 3499.00,
                'stock_qty'   => 140,
                'featured'    => false,
                'weight'      => 0.065,
                'thumbnail'   => 'mock/products/29.jpg',
                'excerpt'     => 'Rugged digital sports watch with Bluetooth, pedometer and calorie tracker.',
                'description' => 'Durable digital sports watch with large LCD display. Bluetooth 4.0 sync with smartphone for call/message notifications. Built-in pedometer, calorie counter, and distance tracker. 50M water resistant. Long battery life up to 6 months. Sporty bi-color silicone strap.',
                'meta_title'       => 'Bluetooth Digital Sports Watch with Pedometer',
                'meta_keywords'    => 'sports watch, digital watch, bluetooth watch, pedometer watch, fitness watch',
                'meta_description' => 'Shop Bluetooth digital sports watch with pedometer and calorie tracker.',
            ],

            // Image 30 - Smart Watch (Electronics - Wearables)
            [
                'title'       => 'Smartwatch with SIM Card Slot & Touch Screen',
                'category_id' => 1,
                'brand_id'    => 1,
                'price'       => 8999.00,
                'sale_price'  => 6999.00,
                'stock_qty'   => 110,
                'featured'    => true,
                'weight'      => 0.055,
                'thumbnail'   => 'mock/products/30.jpg',
                'excerpt'     => 'Full-featured smartwatch with SIM slot, touch display, and health tracking.',
                'description' => 'Feature-packed smartwatch with 1.54" IPS full touch screen. Supports SIM card for calls and messages. Heart rate monitor, sleep tracker, and pedometer. Bluetooth music control, camera remote. Compatible with iOS and Android. White silicone strap with aluminum case.',
                'meta_title'       => 'Smartwatch SIM Card Touch Screen | iOS & Android',
                'meta_keywords'    => 'smartwatch, smart watch, SIM smartwatch, touch screen watch, fitness smartwatch',
                'meta_description' => 'Buy smartwatch with SIM card slot and touch screen at best price.',
            ],

            // Image 31 - Ottoman Footstool (Furniture)
            [
                'title'       => 'Mid-Century Modern Upholstered Ottoman Footstool',
                'category_id' => 6,
                'brand_id'    => 9,
                'price'       => 12999.00,
                'sale_price'  => 9999.00,
                'stock_qty'   => 40,
                'featured'    => false,
                'weight'      => 4.50,
                'thumbnail'   => 'mock/products/31.jpg',
                'excerpt'     => 'Elegant mid-century modern fabric ottoman with walnut-finish legs.',
                'description' => 'Stylish mid-century modern ottoman with beige woven fabric upholstery and solid wood walnut-finish legs. Generously padded seat for comfort. Use as a footrest, extra seating, or accent piece. Assembly required. Dimensions: 45cm x 35cm x 38cm.',
                'meta_title'       => 'Mid-Century Modern Upholstered Ottoman Footstool',
                'meta_keywords'    => 'ottoman, footstool, mid century ottoman, upholstered ottoman, furniture',
                'meta_description' => 'Shop mid-century modern upholstered ottoman footstool with walnut legs.',
            ],

            // Image 32 - Chair Cover (Home & Garden)
            [
                'title'       => 'Stretch Dining Chair Slipcover Floral Print',
                'category_id' => 7,
                'brand_id'    => 9,
                'price'       => 1299.00,
                'sale_price'  => 899.00,
                'stock_qty'   => 350,
                'featured'    => false,
                'weight'      => 0.18,
                'thumbnail'   => 'mock/products/32.jpg',
                'excerpt'     => 'Elastic stretch dining chair cover with stylish floral leaf print.',
                'description' => 'Universal stretch chair slipcover in dark grey with white leaf/floral pattern. Fits most standard dining chairs. Easy to put on and remove. Machine washable spandex-polyester blend. Protects against stains, scratches, and pet hair. Sold individually.',
                'meta_title'       => 'Stretch Dining Chair Slipcover Floral Print',
                'meta_keywords'    => 'chair cover, chair slipcover, dining chair cover, stretch chair cover, home decor',
                'meta_description' => 'Shop stretch dining chair slipcover in floral print. Easy fit and machine washable.',
            ],

            // Image 33 - Unique Console Table (Furniture)
            [
                'title'       => 'Artistic Horse-Leg Console Table with 2 Drawers',
                'category_id' => 6,
                'brand_id'    => 9,
                'price'       => 89999.00,
                'sale_price'  => 74999.00,
                'stock_qty'   => 8,
                'featured'    => true,
                'weight'      => 18.00,
                'thumbnail'   => 'mock/products/33.jpg',
                'excerpt'     => 'Designer console table with sculptural horse-leg design and 2 drawers.',
                'description' => 'Unique artistic console table featuring sculptural curved horse-leg design in high-gloss black lacquer finish. Two smooth-gliding drawers with brass knob handles. Sturdy MDF construction. A bold statement piece for entryways, living rooms, or bedrooms. Dimensions: 90cm x 40cm x 85cm.',
                'meta_title'       => 'Artistic Horse-Leg Console Table | Designer Furniture',
                'meta_keywords'    => 'console table, designer table, artistic furniture, entryway table, accent table',
                'meta_description' => 'Shop artistic horse-leg console table with 2 drawers. Designer statement piece.',
            ],

            // Image 34 - White Cashmere Scarf (Fashion - Accessories)
            [
                'title'       => 'Premium Cashmere Wrap Scarf with Fringe White',
                'category_id' => 3,
                'brand_id'    => 4,
                'price'       => 4499.00,
                'sale_price'  => 3299.00,
                'stock_qty'   => 160,
                'featured'    => false,
                'weight'      => 0.22,
                'thumbnail'   => 'mock/products/34.jpg',
                'excerpt'     => 'Soft premium cashmere wrap scarf in white with fringe trim.',
                'description' => 'Elegant white cashmere blend wrap scarf with classic fringe ends. Oversized and versatile — wear as a scarf, shawl, or beach wrap. Lightweight yet warm. Dry clean only. Available in multiple solid colors. Makes a perfect gift.',
                'meta_title'       => 'Premium Cashmere Wrap Scarf White | Winter Accessories',
                'meta_keywords'    => 'cashmere scarf, white scarf, wrap scarf, fringe scarf, winter accessories',
                'meta_description' => 'Shop premium cashmere wrap scarf in white with fringe trim.',
            ],

            // Image 35 - Facial Steamer (Beauty)
            [
                'title'       => 'Nano Ionic Facial Steamer for Deep Cleansing',
                'category_id' => 4,
                'brand_id'    => 10,
                'price'       => 5999.00,
                'sale_price'  => 4299.00,
                'stock_qty'   => 130,
                'featured'    => true,
                'weight'      => 0.45,
                'thumbnail'   => 'mock/products/35.jpg',
                'excerpt'     => 'Professional nano ionic facial steamer for deep pore cleansing and hydration.',
                'description' => 'Advanced nano ionic facial steamer with large 180ml water tank. Opens pores for deep cleansing and removes blackheads. Adds moisture and improves skin absorption of skincare products. Auto-shutoff safety feature. Steam ready in 30 seconds. Includes measuring cup and nasal inhaler.',
                'meta_title'       => 'Nano Ionic Facial Steamer for Deep Cleansing | Beauty',
                'meta_keywords'    => 'facial steamer, nano ionic steamer, face steamer, skin care, pore cleanser',
                'meta_description' => 'Shop nano ionic facial steamer for deep pore cleansing and hydration.',
            ],

            // Image 36 - Electric Face Brush (Beauty)
            [
                'title'       => 'Electric Rotating Facial Cleansing Brush Set',
                'category_id' => 4,
                'brand_id'    => 10,
                'price'       => 6999.00,
                'sale_price'  => 4999.00,
                'stock_qty'   => 100,
                'featured'    => false,
                'weight'      => 0.28,
                'thumbnail'   => 'mock/products/36.jpg',
                'excerpt'     => 'Rechargeable electric facial cleansing brush with 2 brush heads.',
                'description' => 'Professional electric rotating facial cleansing brush with 3-speed settings. Includes 2 interchangeable brush heads for normal and sensitive skin. Removes makeup, unclogs pores, and exfoliates dead skin cells. USB rechargeable with charging dock. Waterproof for shower use.',
                'meta_title'       => 'Electric Rotating Facial Cleansing Brush Set | Skincare',
                'meta_keywords'    => 'facial brush, cleansing brush, electric face brush, skincare tool, face cleanser',
                'meta_description' => 'Shop electric rotating facial cleansing brush set with 2 heads.',
            ],

            // Image 37 - Glass Travel Mug (Home & Kitchen)
            [
                'title'       => 'Borosilicate Glass Travel Mug with Cork Band 12oz',
                'category_id' => 7,
                'brand_id'    => 9,
                'price'       => 3499.00,
                'sale_price'  => 2699.00,
                'stock_qty'   => 200,
                'featured'    => false,
                'weight'      => 0.32,
                'thumbnail'   => 'mock/products/37.jpg',
                'excerpt'     => 'Eco-friendly borosilicate glass travel mug with natural cork grip band.',
                'description' => 'Sustainable 12oz (340ml) borosilicate glass travel mug with natural cork band for comfortable grip and insulation. Splash-proof lid with sip opening. Dishwasher safe glass body. BPA-free and chemical-free. Perfect for coffee, tea, or smoothies on the go.',
                'meta_title'       => 'Borosilicate Glass Travel Mug Cork Band 12oz | Eco',
                'meta_keywords'    => 'travel mug, glass mug, coffee mug, cork mug, eco friendly mug',
                'meta_description' => 'Shop borosilicate glass travel mug with cork band. Eco-friendly and stylish.',
            ],

            // Image 38 - Baby Rattle (Baby & Toddler)
            [
                'title'       => 'Baby Bunny Musical Rattle with LED Lights',
                'category_id' => 5,
                'brand_id'    => 6,
                'price'       => 1499.00,
                'sale_price'  => 999.00,
                'stock_qty'   => 300,
                'featured'    => false,
                'weight'      => 0.08,
                'thumbnail'   => 'mock/products/38.jpg',
                'excerpt'     => 'Cute bunny-shaped baby rattle with music and flashing LED lights.',
                'description' => 'Adorable bunny-shaped baby rattle with soft silicone body, music, and colorful LED light display. Plays 10+ nursery rhymes and songs. Stimulates auditory and visual development. BPA-free food-grade silicone safe for teething. Available in blue and pink. Suitable from birth.',
                'meta_title'       => 'Baby Bunny Musical Rattle with LED Lights | Infant Toy',
                'meta_keywords'    => 'baby rattle, musical rattle, baby toy, infant toy, bunny rattle',
                'meta_description' => 'Shop baby bunny musical rattle with LED lights. Safe and fun for infants.',
            ],

            // Image 39 - Oil Dispenser (Home & Kitchen)
            [
                'title'       => 'Ceramic Olive Oil Dispenser Bottle 500ml Blue',
                'category_id' => 7,
                'brand_id'    => 9,
                'price'       => 2999.00,
                'sale_price'  => 2199.00,
                'stock_qty'   => 170,
                'featured'    => false,
                'weight'      => 0.60,
                'thumbnail'   => 'mock/products/39.jpg',
                'excerpt'     => 'Elegant ceramic olive oil dispenser with stainless steel pourer spout.',
                'description' => 'Beautiful matte blue ceramic oil dispenser with ergonomic teardrop shape and integrated handle. Stainless steel auto-flip pourer for drip-free pouring. 500ml capacity. Keeps oil fresh and away from light. Suitable for olive oil, vinegar, and other cooking oils. Easy to clean.',
                'meta_title'       => 'Ceramic Olive Oil Dispenser Bottle 500ml Blue',
                'meta_keywords'    => 'oil dispenser, olive oil bottle, ceramic dispenser, kitchen accessories, oil pourer',
                'meta_description' => 'Shop ceramic olive oil dispenser bottle 500ml in blue.',
            ],

            // Image 40 - Baby Teether Ball (Baby & Toddler)
            [
                'title'       => 'Baby Manhattan Soft Teether Rattle Ball Toy',
                'category_id' => 5,
                'brand_id'    => 6,
                'price'       => 1999.00,
                'sale_price'  => 1499.00,
                'stock_qty'   => 250,
                'featured'    => true,
                'weight'      => 0.10,
                'thumbnail'   => 'mock/products/40.jpg',
                'excerpt'     => 'Colorful soft teether rattle ball with easy-grip loops for babies.',
                'description' => 'Classic Manhattan-style baby teether ball with interlocking colorful silicone loops. Easy for tiny hands to grasp, shake, and chew. Rattles gently to stimulate auditory senses. Steam sterilization safe. BPA-free and non-toxic. Suitable for 3 months and up.',
                'meta_title'       => 'Baby Manhattan Soft Teether Rattle Ball Toy',
                'meta_keywords'    => 'baby teether, rattle ball, manhattan toy, teething toy, infant toy',
                'meta_description' => 'Shop baby manhattan soft teether rattle ball. Safe, BPA-free, and steam sterilizable.',
            ],
            // Add these to the $products array in ProductSeeder

            // Image 41 - Lace-Up Crop Sweater (Fashion - Women)
            [
                'title'       => 'Women\'s Lace-Up V-Neck Crop Knit Sweater',
                'category_id' => 2,
                'brand_id'    => 2,
                'price'       => 4499.00,
                'sale_price'  => 3199.00,
                'stock_qty'   => 140,
                'featured'    => false,
                'weight'      => 0.32,
                'thumbnail'   => 'mock/products/41.jpg',
                'excerpt'     => 'Trendy lace-up V-neck crop knit sweater in soft ribbed fabric.',
                'description' => 'Stylish cropped knit sweater with deep V-neck lace-up front detail. Ribbed texture throughout with long sleeves and relaxed fit. Soft acrylic blend fabric. Perfect for casual outings paired with high-waist jeans or skirts. Available in sizes XS-L.',
                'meta_title'       => 'Women\'s Lace-Up V-Neck Crop Knit Sweater',
                'meta_keywords'    => 'crop sweater, lace up sweater, knit sweater, women tops, casual sweater',
                'meta_description' => 'Shop women\'s lace-up V-neck crop knit sweater. Trendy and comfortable.',
            ],

            // Image 42 - Baby Penguin Night Light Plush (Baby & Toddler)
            [
                'title'       => 'Baby Penguin Plush Night Light Sleep Soother',
                'category_id' => 5,
                'brand_id'    => 6,
                'price'       => 3499.00,
                'sale_price'  => 2499.00,
                'stock_qty'   => 180,
                'featured'    => true,
                'weight'      => 0.22,
                'thumbnail'   => 'mock/products/42.jpg',
                'excerpt'     => 'Soft penguin plush toy with glowing belly night light for better baby sleep.',
                'description' => 'Adorable penguin stuffed plush with soft warm belly glow night light. Helps soothe babies to sleep with gentle light. Squeeze belly to activate the light. Super soft machine-washable plush exterior. Available in pink and grey. Suitable from newborn. Battery operated.',
                'meta_title'       => 'Baby Penguin Plush Night Light Sleep Soother',
                'meta_keywords'    => 'baby night light, penguin plush, sleep soother, baby toy, infant toy',
                'meta_description' => 'Shop baby penguin plush night light sleep soother. Helps babies sleep better.',
            ],

            // Image 43 - Ice Cream Cart Toy Set (Baby & Toddler)
            [
                'title'       => 'Kids Ice Cream Cart Pretend Play Toy Set 39pcs',
                'category_id' => 5,
                'brand_id'    => 6,
                'price'       => 5999.00,
                'sale_price'  => 4499.00,
                'stock_qty'   => 100,
                'featured'    => true,
                'weight'      => 1.20,
                'thumbnail'   => 'mock/products/43.jpg',
                'excerpt'     => '39-piece kids ice cream cart pretend play set with umbrella and accessories.',
                'description' => 'Fun 39-piece ice cream cart pretend play set for children aged 3+. Includes rolling cart with umbrella, ice cream cones, popsicles, toppings, and serving accessories. Encourages imaginative play and social skills. Made from non-toxic BPA-free plastic. Easy to assemble.',
                'meta_title'       => 'Kids Ice Cream Cart Pretend Play Toy Set 39pcs',
                'meta_keywords'    => 'kids toy, pretend play, ice cream toy, play set, children toy',
                'meta_description' => 'Shop 39-piece kids ice cream cart pretend play toy set.',
            ],

            // Image 44 - Kids Drum Set (Baby & Toddler)
            [
                'title'       => 'Kids Electric Drum Kit Set with Stool & Microphone',
                'category_id' => 5,
                'brand_id'    => 6,
                'price'       => 12999.00,
                'sale_price'  => 9999.00,
                'stock_qty'   => 60,
                'featured'    => true,
                'weight'      => 3.50,
                'thumbnail'   => 'mock/products/44.jpg',
                'excerpt'     => 'Full kids drum kit with cymbal, stool, microphone and built-in music.',
                'description' => 'Complete children\'s drum kit with bass drum, two tom drums, cymbal, hi-hat, drumsticks, stool, and microphone. Built-in music playback and recording function. Adjustable volume control. Develops rhythm and musical talent in children aged 3-8. Easy assembly required.',
                'meta_title'       => 'Kids Electric Drum Kit Set with Stool & Microphone',
                'meta_keywords'    => 'kids drum set, children drum kit, musical toy, drum toy, kids instrument',
                'meta_description' => 'Shop kids electric drum kit with stool and microphone. Great musical toy.',
            ],

            // Image 45 - TWS Earbuds (Electronics)
            [
                'title'       => 'True Wireless Earbuds with Charging Case Bluetooth 5.0',
                'category_id' => 1,
                'brand_id'    => 1,
                'price'       => 7999.00,
                'sale_price'  => 5999.00,
                'stock_qty'   => 220,
                'featured'    => true,
                'weight'      => 0.055,
                'thumbnail'   => 'mock/products/45.jpg',
                'excerpt'     => 'Premium TWS earbuds with Bluetooth 5.0 and portable charging case.',
                'description' => 'True wireless stereo earbuds with Bluetooth 5.0 for stable low-latency connection. Deep bass with clear highs. Touch controls on each earbud. IPX5 sweat resistance. Single earbud use supported. Charging case provides 4 additional charges for up to 20 hours total playtime.',
                'meta_title'       => 'True Wireless Earbuds Bluetooth 5.0 with Charging Case',
                'meta_keywords'    => 'wireless earbuds, TWS earbuds, bluetooth earbuds, earphones, headphones',
                'meta_description' => 'Buy true wireless earbuds with Bluetooth 5.0 and charging case.',
            ],

            // Image 46 - Hiking Backpack (Fashion - Bags)
            [
                'title'       => 'Waterproof Outdoor Hiking Backpack 40L Yellow',
                'category_id' => 8,
                'brand_id'    => 8,
                'price'       => 8999.00,
                'sale_price'  => 6999.00,
                'stock_qty'   => 130,
                'featured'    => false,
                'weight'      => 0.95,
                'thumbnail'   => 'mock/products/46.jpg',
                'excerpt'     => 'Durable 40L waterproof hiking backpack with multiple compartments.',
                'description' => 'High-capacity 40L hiking backpack in bright yellow and grey. Water-resistant nylon fabric with padded back panel and adjustable shoulder straps. Multiple zippered compartments, side mesh water bottle pockets, and chest/waist straps for stability. Ideal for trekking, camping, and travel.',
                'meta_title'       => 'Waterproof Outdoor Hiking Backpack 40L Yellow',
                'meta_keywords'    => 'hiking backpack, outdoor backpack, 40L backpack, trekking bag, camping backpack',
                'meta_description' => 'Shop waterproof 40L outdoor hiking backpack in yellow. Perfect for trekking.',
            ],

            // Image 47 - High-Top Sneakers Yellow (Fashion - Footwear)
            [
                'title'       => 'Retro Suede High-Top Sneakers Yellow',
                'category_id' => 9,
                'brand_id'    => 5,
                'price'       => 14999.00,
                'sale_price'  => 11999.00,
                'stock_qty'   => 85,
                'featured'    => true,
                'weight'      => 0.55,
                'thumbnail'   => 'mock/products/47.jpg',
                'excerpt'     => 'Classic retro-style high-top suede sneakers with star logo detail.',
                'description' => 'Iconic high-top sneakers in premium yellow suede with contrast star logo on the side. Lace-up closure with padded ankle collar for comfort and support. Rubber vulcanized sole for durability. Vintage off-white sole for retro appeal. Available in UK sizes 4-12.',
                'meta_title'       => 'Retro Suede High-Top Sneakers Yellow | Men & Women',
                'meta_keywords'    => 'high top sneakers, suede sneakers, retro sneakers, yellow sneakers, trainers',
                'meta_description' => 'Shop retro suede high-top sneakers in yellow with classic star logo.',
            ],

            // Image 48 - Men's Windbreaker Jacket (Fashion - Men)
            [
                'title'       => 'Men\'s Hooded Windbreaker Jacket Olive Green',
                'category_id' => 3,
                'brand_id'    => 4,
                'price'       => 11999.00,
                'sale_price'  => 8999.00,
                'stock_qty'   => 75,
                'featured'    => false,
                'weight'      => 0.55,
                'thumbnail'   => 'mock/products/48.jpg',
                'excerpt'     => 'Lightweight men\'s hooded windbreaker jacket in olive green.',
                'description' => 'Versatile men\'s windbreaker jacket in olive green with attached hood. Full-zip front with chin guard, two side hand pockets. Lightweight and packable. Wind and light rain resistant. Relaxed fit suitable for outdoor activities or everyday wear. Available in sizes S-XXL.',
                'meta_title'       => 'Men\'s Hooded Windbreaker Jacket Olive Green',
                'meta_keywords'    => 'windbreaker, men jacket, hooded jacket, olive jacket, lightweight jacket',
                'meta_description' => 'Shop men\'s hooded windbreaker jacket in olive green. Lightweight and versatile.',
            ],

            // Image 49 - Men's Graphic Denim Shirt (Fashion - Men)
            [
                'title'       => 'Men\'s Washed Denim Shirt with Sleeve Print',
                'category_id' => 3,
                'brand_id'    => 4,
                'price'       => 6999.00,
                'sale_price'  => 4999.00,
                'stock_qty'   => 110,
                'featured'    => false,
                'weight'      => 0.38,
                'thumbnail'   => 'mock/products/49.jpg',
                'excerpt'     => 'Vintage-washed denim shirt with bold sleeve graphic print.',
                'description' => 'Relaxed-fit men\'s denim shirt in washed olive/khaki with bold text graphic print on both sleeves. Western-style chest pockets and snap-button cuffs. 100% cotton denim. Worn-in vintage aesthetic. Great for layering over tees or wearing open. Machine washable.',
                'meta_title'       => 'Men\'s Washed Denim Shirt with Sleeve Print',
                'meta_keywords'    => 'denim shirt, men shirt, graphic shirt, washed shirt, casual shirt',
                'meta_description' => 'Shop men\'s washed denim shirt with bold sleeve graphic print.',
            ],

            // Image 50 - Men's Camel Overcoat (Fashion - Men)
            [
                'title'       => 'Men\'s Classic Wool Blend Long Overcoat Camel',
                'category_id' => 3,
                'brand_id'    => 5,
                'price'       => 34999.00,
                'sale_price'  => 27999.00,
                'stock_qty'   => 35,
                'featured'    => true,
                'weight'      => 1.60,
                'thumbnail'   => 'mock/products/50.jpg',
                'excerpt'     => 'Sophisticated men\'s wool blend long overcoat in classic camel.',
                'description' => 'Timeless men\'s long overcoat in premium wool-blend fabric. Single-breasted notch lapel with concealed button closure. Welt pockets and fully lined interior. Slim to regular fit. Perfect for formal and smart-casual occasions. Dry clean only. Available in sizes S-XXL.',
                'meta_title'       => 'Men\'s Classic Wool Blend Long Overcoat Camel',
                'meta_keywords'    => 'men overcoat, wool coat, camel coat, long coat, winter coat men',
                'meta_description' => 'Shop men\'s classic wool blend long overcoat in camel.',
            ],

            // Image 51 - Twist Front Sweater Mustard (Fashion - Women)
            [
                'title'       => 'Women\'s Twist Front V-Neck Knit Sweater Mustard',
                'category_id' => 2,
                'brand_id'    => 2,
                'price'       => 4999.00,
                'sale_price'  => 3499.00,
                'stock_qty'   => 155,
                'featured'    => false,
                'weight'      => 0.38,
                'thumbnail'   => 'mock/products/51.jpg',
                'excerpt'     => 'Chic twist-front V-neck knit sweater in warm mustard yellow.',
                'description' => 'Trendy women\'s knit sweater with unique twist-knot front detail and V-neckline. Long sleeves with ribbed cuffs and hem. Soft chunky ribbed knit fabric in warm mustard yellow. Relaxed oversized fit. Pairs perfectly with jeans or midi skirts. Machine washable.',
                'meta_title'       => 'Women\'s Twist Front V-Neck Knit Sweater Mustard',
                'meta_keywords'    => 'twist sweater, knit sweater, mustard sweater, women tops, v-neck sweater',
                'meta_description' => 'Shop women\'s twist front V-neck knit sweater in mustard yellow.',
            ],

            // Image 52 - Lace-Up Crop Sweater variant (Fashion - Women)
            [
                'title'       => 'Women\'s Lace-Up Deep V Crop Sweater Pink',
                'category_id' => 2,
                'brand_id'    => 2,
                'price'       => 4499.00,
                'sale_price'  => 3199.00,
                'stock_qty'   => 130,
                'featured'    => false,
                'weight'      => 0.32,
                'thumbnail'   => 'mock/products/52.jpg',
                'excerpt'     => 'Cropped lace-up deep V-neck knit sweater in blush pink.',
                'description' => 'Flirty cropped knit sweater with deep V lace-up front and long sleeves. Ribbed chunky knit fabric in soft blush pink. Relaxed boxy fit with raw-edge hem. Style with high-waist bottoms for a balanced look. Soft acrylic blend. Available in sizes XS-L.',
                'meta_title'       => 'Women\'s Lace-Up Deep V Crop Sweater Pink',
                'meta_keywords'    => 'crop sweater, lace up sweater, pink sweater, v neck sweater, women knitwear',
                'meta_description' => 'Shop women\'s lace-up deep V crop sweater in blush pink.',
            ],

            // Image 53 - Women's Military Jacket (Fashion - Women)
            [
                'title'       => 'Women\'s Oversized Military Shirt Jacket Khaki',
                'category_id' => 2,
                'brand_id'    => 2,
                'price'       => 9999.00,
                'sale_price'  => 7499.00,
                'stock_qty'   => 90,
                'featured'    => false,
                'weight'      => 0.65,
                'thumbnail'   => 'mock/products/53.jpg',
                'excerpt'     => 'Oversized military-style shirt jacket with large front pockets in khaki.',
                'description' => 'Relaxed oversized military shirt jacket in washed khaki green. Features four large flap chest pockets with button closures and roll-up sleeve tabs. Point collar with full button-down front. Heavy cotton twill fabric. Great as a layer over basics or as a light jacket.',
                'meta_title'       => 'Women\'s Oversized Military Shirt Jacket Khaki',
                'meta_keywords'    => 'military jacket, shirt jacket, khaki jacket, oversized jacket, women outerwear',
                'meta_description' => 'Shop women\'s oversized military shirt jacket in khaki.',
            ],

            // Image 54 - Cable Knit Scarf Grey (Fashion - Accessories)
            [
                'title'       => 'Unisex Cable Knit Winter Scarf Charcoal Grey',
                'category_id' => 3,
                'brand_id'    => 4,
                'price'       => 2499.00,
                'sale_price'  => 1699.00,
                'stock_qty'   => 250,
                'featured'    => false,
                'weight'      => 0.25,
                'thumbnail'   => 'mock/products/54.jpg',
                'excerpt'     => 'Classic cable knit unisex winter scarf in charcoal grey.',
                'description' => 'Warm and stylish unisex cable knit scarf in charcoal grey. Soft acrylic-wool blend with textured cable pattern throughout. Long wrap length for versatile styling. Machine washable. Perfect for men and women. Great everyday winter accessory or gift.',
                'meta_title'       => 'Unisex Cable Knit Winter Scarf Charcoal Grey',
                'meta_keywords'    => 'cable knit scarf, winter scarf, grey scarf, unisex scarf, knit scarf',
                'meta_description' => 'Shop unisex cable knit winter scarf in charcoal grey.',
            ],

            // Image 55 - Yellow Cap (Fashion - Accessories)
            [
                'title'       => 'Streetwear Logo Baseball Cap with Ribbon Strap Yellow',
                'category_id' => 3,
                'brand_id'    => 4,
                'price'       => 1999.00,
                'sale_price'  => 1499.00,
                'stock_qty'   => 300,
                'featured'    => false,
                'weight'      => 0.12,
                'thumbnail'   => 'mock/products/55.jpg',
                'excerpt'     => 'Bold yellow streetwear baseball cap with ribbon detail and logo print.',
                'description' => 'Eye-catching yellow baseball cap with script logo embroidery on front and long yellow ribbon strap detail. Structured 6-panel construction with adjustable back closure. 100% cotton twill. Unisex design. One size fits most. Perfect for streetwear and casual looks.',
                'meta_title'       => 'Streetwear Logo Baseball Cap Yellow | Unisex',
                'meta_keywords'    => 'baseball cap, yellow cap, streetwear cap, logo cap, unisex cap',
                'meta_description' => 'Shop streetwear logo baseball cap with ribbon strap in yellow.',
            ],

            // Image 56 - Bear Print Sweater (Fashion - Women)
            [
                'title'       => 'Women\'s Bear Print Colorblock Oversized Sweater',
                'category_id' => 2,
                'brand_id'    => 2,
                'price'       => 5499.00,
                'sale_price'  => 3999.00,
                'stock_qty'   => 120,
                'featured'    => false,
                'weight'      => 0.45,
                'thumbnail'   => 'mock/products/56.jpg',
                'excerpt'     => 'Cute bear-print colorblock oversized knit sweater in cream and mustard.',
                'description' => 'Adorable oversized sweater with cute bear graphic print on sleeves and colorblock design in cream, mustard, and white. Soft mohair-like fluffy knit fabric. Wide crew neckline and relaxed boxy fit. Ribbed cuffs and hem. Perfect for cozy casual days.',
                'meta_title'       => 'Women\'s Bear Print Colorblock Oversized Sweater',
                'meta_keywords'    => 'bear sweater, oversized sweater, colorblock sweater, cute sweater, women knitwear',
                'meta_description' => 'Shop women\'s bear print colorblock oversized sweater.',
            ],

            // Image 57 - Hiking Backpack variant (Fashion - Bags)
            [
                'title'       => 'Waterproof Outdoor Hiking Backpack 45L Yellow',
                'category_id' => 8,
                'brand_id'    => 8,
                'price'       => 9999.00,
                'sale_price'  => 7999.00,
                'stock_qty'   => 110,
                'featured'    => true,
                'weight'      => 1.05,
                'thumbnail'   => 'mock/products/57.jpg',
                'excerpt'     => 'Heavy-duty 45L waterproof hiking backpack with chest and waist straps.',
                'description' => 'Premium 45L hiking backpack in yellow and dark grey. Reinforced water-resistant nylon with ventilated mesh back panel. Padded shoulder straps, adjustable chest strap, and waist belt for load distribution. Laptop compartment fits up to 15.6". Multiple pockets for organization.',
                'meta_title'       => 'Waterproof Outdoor Hiking Backpack 45L Yellow',
                'meta_keywords'    => 'hiking backpack, 45L backpack, outdoor bag, camping bag, trekking backpack',
                'meta_description' => 'Shop heavy-duty 45L waterproof hiking backpack in yellow.',
            ],

            // Image 58 - Men's Windbreaker Full View (Fashion - Men)
            [
                'title'       => 'Men\'s Lightweight Hooded Windbreaker Jacket Sage',
                'category_id' => 3,
                'brand_id'    => 4,
                'price'       => 12999.00,
                'sale_price'  => 9999.00,
                'stock_qty'   => 70,
                'featured'    => false,
                'weight'      => 0.58,
                'thumbnail'   => 'mock/products/58.jpg',
                'excerpt'     => 'Men\'s packable lightweight hooded windbreaker in sage green.',
                'description' => 'Clean and minimal men\'s hooded windbreaker in sage olive green. Full-zip design with adjustable hood, two hand pockets, and one chest pocket. Lightweight ripstop fabric that is wind and water resistant. Packable into its own pocket. Great for travel and outdoor activities.',
                'meta_title'       => 'Men\'s Lightweight Hooded Windbreaker Jacket Sage Green',
                'meta_keywords'    => 'windbreaker, men jacket, sage green jacket, hooded windbreaker, packable jacket',
                'meta_description' => 'Shop men\'s lightweight hooded windbreaker jacket in sage green.',
            ],

            // Image 59 - High-Top Sneakers front view (Fashion - Footwear)
            [
                'title'       => 'Retro Suede High-Top Sneakers Yellow Front View',
                'category_id' => 9,
                'brand_id'    => 5,
                'price'       => 14999.00,
                'sale_price'  => 11999.00,
                'stock_qty'   => 80,
                'featured'    => false,
                'weight'      => 0.55,
                'thumbnail'   => 'mock/products/59.jpg',
                'excerpt'     => 'Classic retro high-top suede sneakers in bold yellow — front view.',
                'description' => 'Iconic retro high-top sneakers in rich yellow suede leather. Classic star emblem on ankle, lace-up front with padded tongue and collar. Vulcanized rubber outsole with vintage cream finish. Unisex sizing available. UK sizes 4-12.',
                'meta_title'       => 'Retro Suede High-Top Sneakers Yellow | Classic Style',
                'meta_keywords'    => 'high top sneakers, suede sneakers, yellow trainers, retro shoes, classic sneakers',
                'meta_description' => 'Shop retro suede high-top sneakers in bold yellow.',
            ],

            // Image 60 - Twist Front Sweater variant (Fashion - Women)
            [
                'title'       => 'Women\'s Twist Front V-Neck Knit Sweater Dark Mustard',
                'category_id' => 2,
                'brand_id'    => 2,
                'price'       => 4999.00,
                'sale_price'  => 3499.00,
                'stock_qty'   => 145,
                'featured'    => false,
                'weight'      => 0.38,
                'thumbnail'   => 'mock/products/60.jpg',
                'excerpt'     => 'Cozy twist-front V-neck knit sweater in deep dark mustard.',
                'description' => 'Women\'s relaxed-fit knit sweater with stylish twist-knot front hem and V-neckline. Chunky ribbed knit in deep dark mustard. Long sleeves with ribbed cuffs. Soft and warm acrylic blend. Easy to style with denim, trousers, or layered over a shirt. Machine washable.',
                'meta_title'       => 'Women\'s Twist Front V-Neck Knit Sweater Dark Mustard',
                'meta_keywords'    => 'twist sweater, knit sweater, dark mustard sweater, v neck sweater, women knitwear',
                'meta_description' => 'Shop women\'s twist front V-neck knit sweater in dark mustard.',
            ],
            // Add these to the $products array in ProductSeeder

            // Image 61 - Puff Sleeve White Top & Straw Hat outfit (Fashion - Women)
            [
                'title'       => 'Women\'s Puff Sleeve Ruffle Crop Top White',
                'category_id' => 2,
                'brand_id'    => 2,
                'price'       => 3999.00,
                'sale_price'  => 2999.00,
                'stock_qty'   => 160,
                'featured'    => true,
                'weight'      => 0.18,
                'thumbnail'   => 'mock/products/61.jpg',
                'excerpt'     => 'Elegant white puff sleeve ruffle crop top with ribbed knit body.',
                'description' => 'Chic white crop top with dramatic puff sleeves featuring delicate ruffle trim. Ribbed knit body with off-shoulder neckline. Light and airy fabric perfect for spring and summer. Pairs beautifully with wide-leg trousers or high-waist skirts. Available in sizes XS-L.',
                'meta_title'       => 'Women\'s Puff Sleeve Ruffle Crop Top White',
                'meta_keywords'    => 'puff sleeve top, crop top, white top, ruffle top, women fashion',
                'meta_description' => 'Shop women\'s puff sleeve ruffle crop top in white. Elegant and stylish.',
            ],

            // Image 62 - Cross Strap V-Neck Knit Sweater Grey (Fashion - Women)
            [
                'title'       => 'Women\'s Cross Strap V-Neck Knit Sweater Grey',
                'category_id' => 2,
                'brand_id'    => 2,
                'price'       => 4499.00,
                'sale_price'  => 3299.00,
                'stock_qty'   => 145,
                'featured'    => false,
                'weight'      => 0.35,
                'thumbnail'   => 'mock/products/62.jpg',
                'excerpt'     => 'Soft grey V-neck knit sweater with criss-cross strap front detail.',
                'description' => 'Relaxed-fit knit sweater in heather grey with a unique criss-cross strap V-neckline. Ribbed texture throughout with drop shoulders and long sleeves. Soft acrylic blend fabric. Versatile wardrobe staple — pairs with jeans, trousers, or skirts. Machine washable. Available in sizes XS-XL.',
                'meta_title'       => 'Women\'s Cross Strap V-Neck Knit Sweater Grey',
                'meta_keywords'    => 'cross strap sweater, v neck sweater, grey sweater, knit sweater, women tops',
                'meta_description' => 'Shop women\'s cross strap V-neck knit sweater in grey.',
            ],

            // Image 63 - Beaded Clutch Bag (Fashion - Bags)
            [
                'title'       => 'Handcrafted Pearl Beaded Half-Moon Clutch Bag',
                'category_id' => 8,
                'brand_id'    => 8,
                'price'       => 6999.00,
                'sale_price'  => 4999.00,
                'stock_qty'   => 70,
                'featured'    => true,
                'weight'      => 0.30,
                'thumbnail'   => 'mock/products/63.jpg',
                'excerpt'     => 'Elegant handcrafted pearl and bead embellished half-moon clutch with wooden ring handle.',
                'description' => 'Luxurious half-moon shaped clutch bag fully embellished with white pearl beads and shell embroidery. Wooden ring top handle with detachable silver chain strap for crossbody wear. Fully lined interior with zip closure. Perfect for weddings, parties, and evening events. Handcrafted.',
                'meta_title'       => 'Handcrafted Pearl Beaded Half-Moon Clutch Bag',
                'meta_keywords'    => 'beaded clutch, pearl bag, clutch bag, evening bag, wedding bag',
                'meta_description' => 'Shop handcrafted pearl beaded half-moon clutch bag with wooden handle.',
            ],
        ];

        foreach ($products as $index => $product) {

            $sku        = $product['sku']        ?? 'SKU-' . strtoupper(Str::random(6));
            $sale_price = $product['sale_price'] ?? null;
            $thumbnail  = $product['thumbnail']  ?? null;

            DB::table('products')->insert(array_merge([
                'slug'       => Str::slug($product['title'] . ' ' . $sku),
                'sku'        => $sku,
                'thumbnail2' => $thumbnail ? preg_replace('/(\.\w+)$/', '_1$1', $thumbnail) : null,
                // 'cost'       => $sale_price ? round($sale_price * 0.60, 2) : null,
                'cost' => $sale_price ? intval(round($sale_price * 0.60)) : null,

                'warehouse_id'      => rand(1, 3),
                'shipping_class_id' => rand(1, 3),          
                'low_stock_alert'   => rand(1, 10),
                'backorderable'     => (bool) rand(0, 1),
                'is_global'         => (bool) rand(0, 1),
                'return_policy'     => $policies[array_rand($policies)],
                'warranty_period'      => rand(0, 12),
                'warranty_period_unit' => rand(1, 4),
                'warranty_type'        => rand(1, 2),
                'return_able'          => (bool) rand(0, 1),
                'upsellable'           => (bool) rand(0, 1),
                'cross_sellable'       => (bool) rand(0, 1),
                'min_purchase'         => rand(1, 5),
                'max_purchase'         => rand(1, 50),

                'is_active'          => true,
                'sort_by'            => $index + 1,
                'type'               => 1,
                'created_at'         => $now,
                'updated_at'         => $now,
            ], $product));
        }
    }
}
